### PR TITLE
Add unresolved package message

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by harshad16** [comment]
pytest failure:

```
Installed /workspace/repo/.eggs/colorlog-2.10.0-py3.6.egg
running egg_info
creating thoth_messaging.egg-info
writing thoth_messaging.egg-info/PKG-INFO
writing dependency_links to thoth_messaging.egg-info/dependency_links.txt
writing requirements to thoth_messaging.egg-info/requires.txt
writing top-level names to thoth_messaging.egg-info/top_level.txt
writing manifest file '\''thoth_messaging.egg-info/SOURCES.txt'\''
reading manifest file '\''thoth_messaging.egg-info/SOURCES.txt'\''
writing manifest file '\''thoth_messaging.egg-info/SOURCES.txt'\''
running build_ext
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    command_options={"build_sphinx": {"version": ("setup.py", VERSION), "release": ("setup.py", VERSION)}},
  File "/opt/app-root/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/test.py", line 225, in run
    with self.project_on_sys_path():
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/test.py", line 164, in project_on_sys_path
    require('\''%s==%s'\'' % (ei_cmd.egg_name, ei_cmd.egg_version))
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (click 6.6 (/workspace/repo/.eggs/click-6.6-py3.6.egg), Requirement.parse('\''click<8.0,>=6.7'\''), {'\''faust'\''})'
```

**Comment by pacospace** [comment]
> pytest failure:
> 
> ```
> Installed /workspace/repo/.eggs/colorlog-2.10.0-py3.6.egg
> running egg_info
> creating thoth_messaging.egg-info
> writing thoth_messaging.egg-info/PKG-INFO
> writing dependency_links to thoth_messaging.egg-info/dependency_links.txt
> writing requirements to thoth_messaging.egg-info/requires.txt
> writing top-level names to thoth_messaging.egg-info/top_level.txt
> writing manifest file '\''thoth_messaging.egg-info/SOURCES.txt'\''
> reading manifest file '\''thoth_messaging.egg-info/SOURCES.txt'\''
> writing manifest file '\''thoth_messaging.egg-info/SOURCES.txt'\''
> running build_ext
> Traceback (most recent call last):
>   File "setup.py", line 75, in <module>
>     command_options={"build_sphinx": {"version": ("setup.py", VERSION), "release": ("setup.py", VERSION)}},
>   File "/opt/app-root/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/test.py", line 225, in run
>     with self.project_on_sys_path():
>   File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
>     return next(self.gen)
>   File "/opt/app-root/lib/python3.6/site-packages/setuptools/command/test.py", line 164, in project_on_sys_path
>     require('\''%s==%s'\'' % (ei_cmd.egg_name, ei_cmd.egg_version))
>   File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/opt/app-root/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (click 6.6 (/workspace/repo/.eggs/click-6.6-py3.6.egg), Requirement.parse('\''click<8.0,>=6.7'\''), {'\''faust'\''})'
> ```

mmm how do I replicate it? locally I don't find any issue installing with pipenv

**Comment by KPostOffice** [comment]
^^
@harshad16 @pacospace 
This looks similar to the issue we ran into before.  I think it was due to `thoth-lab`?

**Comment by pacospace** [comment]
> ^^
> @harshad16 @pacospace
> This looks similar to the issue we ran into before. I think it was due to `thoth-lab`?

we do not have thoth-lab here, but yes you are right @KPostOffice it is the same issue and it's coala-bear which require a specific version of click. I will remove it from dev-packages

**Pull request merged**
