### PR TITLE
change message contents of inspection complete

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

https://github.com/thoth-station/thoth-application/issues/398

## This introduces a breaking change

- [ ] Yes
- [x] No

## Has a Message Class been changed? Version incremented? 

- [x] Yes
- [ ] No

## This should yield a new module release

- [x] Yes
- [ ] No

## This Pull Request implements

I lost track of this issue and was working through it again and the original message contents that I established don't make sense with the requirements on investigator side. This does not require a new version of the message as it hasn't been produced at all yet.

Current KPostOffice: :brain: 
Past KPostOffice: :man_facepalming:

### CODE REVIEW

**Comment by KPostOffice** [comment]
Investigator will just call `thoth.common.openshift.schedule_graph_sync` which only requires the document id and optionally whether or not to force sync.

**Comment by KPostOffice** [comment]
https://github.com/thoth-station/thoth-application/issues/398

**Review by pacospace — COMMENTED** [review]
lgtm! 🥇

**Comment by pacospace** [comment]
please take a look at pre commit.

**Comment by KPostOffice** [comment]
@pacospace PTAL

**Review by pacospace — APPROVED** [review]

**Comment by pacospace** [comment]
Thanks @KPostOffice

**Pull request merged**
