### PR TITLE
add kebechet meta

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

https://github.com/thoth-station/investigator/pull/468
https://github.com/thoth-station/thamos/pull/753
https://github.com/thoth-station/kebechet/pull/699

### CODE REVIEW

**Comment by KPostOffice** [comment]
Technically we do have the actual schema for `kebechet_metadata` if we want to use it here.  Though it does just represent a function argument in this case

**Review by harshad16 — COMMENTED** [review]
/lgtm

**Pull request merged**
