### PR TITLE
using jsonschema instead of python classes

### PR DESCRIPTION
**Pull request by KPostOffice**
## Related Issues and Dependencies

https://github.com/thoth-station/messaging/pull/347

## This introduces a breaking change

- [x] Yes
- [ ] No

## Has a Message Class been changed? Version incremented?

- [ ] Yes
- [x] No

## This should yield a new module release

- [x] Yes
- [ ] No

## This Pull Request implements

As discussed with @fridex we could use jsonschema as an alternative to the current message specification.  This allows for deeply nested json that follows explicit rules.

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
Thanks! :+1: 

The approach looks good to me. It might be also better than just simple attr classes as they do not enforce types (they do type hinting, but I'm not sure if type checking can be enforced). This is completely fine with attrs:

```python
import attr

@attr.s(slots=True)
class Foo:
    num = attr.ib(type=int)

obj = Foo(num="Some string which should be a number")
print(obj.num)
```

jsonschema can give us more power and control over messages and will prevent from scheduling/receiving messages that do not conform to declared schema. BTW I would expect library behind message passing to do this automatically (provide a mechanism to declare message schema).

**Comment by KPostOffice** [comment]
```
from typing import TypedDict, Optional

class Foo(TypedDict, total=True):
    a: int
    b: str

class BarRequired(TypedDict, total=True):
    c: Foo
    d: int

class Bar(BarRequired, total=False):
    optional: str

test: Bar = {"c": {"a": 6, "b": "baz"}, "d": 5, "optional": "hello"}
```
This allows for specifying inheritance as well as required vs optional dict elements.

**Comment by fridex** [comment]
BTW what about using pydantic here? https://pydantic-docs.helpmanual.io/

**Comment by KPostOffice** [comment]
Use pydantic instead

**Pull request closed without merging**
